version: '3.7'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./output_files:/output
      - ./GeoIP:/usr/share/GeoIP:ro
    command: parsedmarc -c /parsedmarc.ini
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=<user>
      - GF_SECURITY_ADMIN_PASSWORD=<password>

  geoipupdate:
    image: maxmindinc/geoipupdate:latest
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=<ID>
      - GEOIPUPDATE_LICENSE_KEY=<KEY>
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - ${USERDIR}/dmarc-visualizer/GeoIP:/usr/share/GeoIP
